[package]
name = "kayen"
version = "0.1.0"
authors = ["Louis Bellet <lbellet@heliostech.fr>"]

[dependencies]
iron = "0.5.1"
bodyparser = "0.7.0"
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
exonum = "0.2.0"
